TwilioCheckout/Controllers/KeyController.cs
using System.Configuration;
using System.Web.Mvc;
using TwilioCheckout.Models;
using Twilio;

namespace TwilioCheckout.Controllers
{
    public class KeyController : Controller
    {
        // GET: Key
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(KeyModels model, string returnUrl)
        {
            string AccountSID = ConfigurationManager.AppSettings["AccountSID"];
            string AuthToken = ConfigurationManager.AppSettings["AuthToken"];
            string phoneNumber = ConfigurationManager.AppSettings["phoneNumber"];

            var client = new TwilioRestClient(AccountSID, AuthToken);
            client.SendMessage(phoneNumber, model.PhoneNumber, model.Message);
            return View("Success");
        }
    }
}

TwilioCheckout/Views/Key/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@model TwilioCheckout.Models.KeyModels
<div class="col-sm-10">
    @using (Html.BeginForm("Index", "Key", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
        @Html.AntiForgeryToken()
        <h4>Send SMS</h4>
        <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.PhoneNumber, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
                       
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Message, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(m => m.Message, new { @class = "form-control" })
                     
                    </div>
                </div>
               
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Send Sms" class="btn btn-default" />
                    </div>
                </div>
               
              
    }

</div>

TwilioCheckout/Views/Key/Success.cshtml
@{
    ViewBag.Title = "Success";
}

<h1>Success</h1>